/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.io.File;
import java.io.FileWriter;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Random;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author david
 */
public class frm_aleatorio extends javax.swing.JFrame {
    
    public frm_aleatorio() {
        initComponents();
        this.setTitle("GENERADOR DE NUMEROS ALEATORIOS UMG VER.2.0");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_principal = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panel_principal.setBackground(new java.awt.Color(0, 153, 255));

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jButton1.setText("Generar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 204, 51));
        jButton2.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jButton2.setText("Ordenar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_principalLayout = new javax.swing.GroupLayout(Panel_principal);
        Panel_principal.setLayout(Panel_principalLayout);
        Panel_principalLayout.setHorizontalGroup(
            Panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_principalLayout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addGroup(Panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        Panel_principalLayout.setVerticalGroup(
            Panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_principalLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked

        //-------------------------------------->Genera 1000000 Numeros Aleatorios 
        File file = new File("AleatorioDesordenado.txt");
        try{file.createNewFile();}catch (Exception ex) {}
        Random aleatorio = new Random();
        ArrayList<Integer> arreglo = new ArrayList<>();
        //System.out.println(+aleatorio.nextInt(10000000-(-10000000)));
        for (int i=1; i<=1000000; i++){
            int value = aleatorio.nextInt(10000000-(-10000000)+1)+(-10000000);
            arreglo.add(value);
        }
        /*if(!f.exists()){
            try {
                f.createNewFile();
            } catch (IOException e) {
                Logger.getLogger("Error... "+e.getMessage());
            }
        }*/
        
        /*System.out.println(arreglo.get(5000));
        System.out.println(arreglo.get(10000));
        System.out.println(arreglo.get(900000));*/
        //FileWriter fw = new FileWriter(File fi);
        //String str = "";
        /*for(String cad : arreglo){
            
        }*/
        //-------------------------------------->Escribe el Array dentro del archivo
        try{
           FileWriter writer = new FileWriter(file);
            //writer.write(arreglo.hashCode()); --->No funciono
            writer.write(arreglo.toString());
            writer.flush();
            writer.close();
            //Collections.sort(arreglo);
            //System.out.println(arreglo);
            JOptionPane.showMessageDialog(rootPane, "Numeros Generados Exitosamente","Mensaje",JOptionPane.INFORMATION_MESSAGE);
        }catch (Exception ex) {
            
        }
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        //-------------------------------------->Lee el archivo
        
        //FileReader fr = new FileReader("D:\\david\\Documents\\UNIVERSIDAD\\Quinto Semestre\\Programacion_III\\Semana 2 (07-02 AL 11-02)\\Generador_de_numeros_aleatorios_umg\\AleatorioDesordenado.txt");
        /*FileReader fr = new FileReader(file);
        ArrayList<Integer> arregloArreglado = new ArrayList<>();*/
        //for (int a=1; a<=1000000; a++){
            //int value = aleatorio.nextInt(10000000-(-10000000)+1)+(-10000000);
            /*String cadena = "";
            int value = fr.read();
            while(value != -1){
              //arregloArreglado += (char) value;  
                    cadena += (char) value;
                    value = fr.read();
            }*/
            //arregloArreglado.add(value);
        //}
        /*String cadena = fr.toString();
        
        System.out.println(cadena);
        System.out.println(arregloArreglado);*/
        
        //prueba #1 hacerlo con "readAllLines"###############################################
        /*try{
            
            ArrayList<String> lineas = new ArrayList<>(Files.readAllLines(Paths.get("D:\\david\\Documents\\UNIVERSIDAD\\Quinto Semestre\\Programacion_III\\Semana 2 (07-02 AL 11-02)\\Generador_de_numeros_aleatorios_umg\\AleatorioDesordenado.txt")));
            Collections.sort(lineas);
            //System.out.println(lineas);
            ArrayList<String> lineas2 = new ArrayList<>(Files.readAllLines(Paths.get("D:\\david\\Documents\\UNIVERSIDAD\\Quinto Semestre\\Programacion_III\\Semana 2 (07-02 AL 11-02)\\Generador_de_numeros_aleatorios_umg\\Hola.txt")));
            Collections.sort(lineas2);
            System.out.println(lineas2);
            //ArrayList<Integer> resultado = getIntegerArray(lineas);
            //System.out.println(resultado);
        }catch (Exception e) {
            System.out.println("Error.... "+e.getMessage());
        }*/
        //ArrayList<Integer> resultado = getIntegerArray(lineas);
        
        //prueba#2 hacerlo con "Scanner"######################################################
        File fileO = new File("AleatorioOrdenado.txt");
        try{fileO.createNewFile();}catch (Exception ex) {}
        
        ArrayList<String> lineas = new ArrayList<>();
        try(Scanner s = new Scanner(new File("AleatorioDesordenado.txt")).useDelimiter(",")){
            while(s.hasNext()){
                lineas.add(s.next());
            }
        }catch (Exception e) {
            System.out.println("Error.... "+e.getMessage());
        }
        ArrayList<Integer> resultado = getIntegerArray(lineas);
        //Collections.sort(lineas);
        //System.out.println(lineas);
        Collections.sort(resultado);
        //System.out.println(resultado);
        try{
            FileWriter writerO = new FileWriter(fileO);
            writerO.write(resultado.toString());
            writerO.flush();
            writerO.close();
            JOptionPane.showMessageDialog(rootPane, "Numeros Ordenados Exitosamente","Mensaje",JOptionPane.INFORMATION_MESSAGE);
        }catch (Exception ex) {
            
        }
        
    }//GEN-LAST:event_jButton2MouseClicked

    public static ArrayList<Integer> getIntegerArray(ArrayList<String>stringArray){
        ArrayList<Integer> result = new ArrayList<Integer>();
        for(String stringValue : stringArray){
            try{
                result.add(Integer.parseInt(stringValue.trim()));
            }catch (Exception ex) {
                //System.out.println("No se pudo compa" + ex.getMessage());
            }
        }
        return result;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_aleatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_aleatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_aleatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_aleatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_aleatorio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel_principal;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables
}
